version: '3.8'

services:
  mongodb:
    image: mongodb/mongodb-atlas-local:8.0.1
    container_name: job-portal-mongodb
    restart: unless-stopped
    ports:
      - "27018:27017"
    environment:
      - MONGODB_INITDB_ROOT_USERNAME=user
      - MONGODB_INITDB_ROOT_PASSWORD=pass
      - RUNNER_LOG_FILE=/dev/stderr
    volumes:
      - mongodb_data:/data/db
    networks:
      - job-portal

volumes:
  mongodb_data:

networks:
  job-portal:
    driver: bridge